pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/Bindesh-Allerin/Rotur_Automation.git'
            }
        }

        stage('Build & Test') {
            steps {
            script{
            if(isUnix()){
                sh 'mvn clean test'
            }else{
                bat 'mvn clean test'
            }}}
        }

        stage('Publish Report') {
            steps {
                publishHTML([
                    reportDir: 'Com.Rotur/test-output/reports',
                    reportFiles: 'ExtentReport.html',
                    reportName: 'Rotur Test Automation Report'
                ])
            }
        }
    }
}
